id: I0F7FB48E
ocr_import_info:
  timestamp: '2023-09-23T05:45:46.741894+00:00'
  batch_id: batch-7a6b
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-23 06:14:31.406858+00:00
last_modified: 2023-09-23 06:14:31.406865+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM1420
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM1420
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བསྟན་བཅོས་ཆེན་པོ་དབུ་མ་ལ་འཇུག་པའི་ཚིག་འགྲེལ་ཟླ་བའི་འོད་ཟེར་སོགས།
  languages:
  - bo
  author: བཙུན་གཟུགས་བློ་བཟང་སྦྱིན་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9577731237562259
  ocr_word_median_confidence_index: 0.997357525
bases:
  I1NLM1420_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM1420_001
      total_pages: 244
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM1420_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.997357525
      ocr_word_mean_confidence_index: 0.9577731237562259
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
